<div id="addressFinderBilling" class="addressFinder">
    <div class="postcode clearfix" style="display: none;">
        <label for="billing:addressFinderPostcode"><?php echo $this->__('Address Finder') ?></label>
        <div class="input-box">
            <input type="text" id="billing:addressFinderPostcode" class="input-text" name="billing[addressFinderPostcode]" title="<?php echo $this->__('Enter Your Post Code') ?>" value="<?php echo $this->__('Enter Your Post Code') ?>" onfocus="javascript:if(this.value == '<?php echo $this->__('Enter Your Post Code') ?>'){ this.value= ''; }" onblur="javascript:if(this.value == ''){ this.value= '<?php echo $this->__('Enter Your Post Code') ?>'; }" />
        </div>
        <button class="button" title="<?php echo $this->__('Find Address') ?>" type="button" onclick="findAddressFromPostcode($('billing:addressFinderPostcode').value, 'billing');">
            <span><span><?php echo $this->__('Find Address') ?></span></span>
        </button>
    </div>
    <div class="addressList clearfix"></div>
</div>

<div id="addressFinderShipping" class="addressFinder">
    <div class="postcode clearfix" style="display: none;">
        <label for="shipping:addressFinderPostcode"><?php echo $this->__('Address Finder') ?></label>
        <div class="input-box">
            <input type="text" id="shipping:addressFinderPostcode" class="input-text" name="shipping[addressFinderPostcode]" title="<?php echo $this->__('Enter Your Post Code') ?>" value="<?php echo $this->__('Enter Your Post Code') ?>" onfocus="javascript:if(this.value == '<?php echo $this->__('Enter Your Post Code') ?>'){ this.value= ''; }" onblur="javascript:if(this.value == ''){ this.value= '<?php echo $this->__('Enter Your Post Code') ?>'; }" />
        </div>
        <button class="button" title="<?php echo $this->__('Find Address') ?>" type="button" onclick="findAddressFromPostcode($('shipping:addressFinderPostcode').value, 'shipping');">
            <span><span><?php echo $this->__('Find Address') ?></span></span>
        </button>
    </div>
    <div class="addressList clearfix"></div>
</div>

<script type="text/javascript">
//<![CDATA[
    var $billingAddressForm = $('billing-new-address-form');
    var $addressFinderBilling = $('addressFinderBilling');
    var $billingPostcode = $addressFinderBilling.select('.postcode')[0];
    var $billingAddressList = $addressFinderBilling.select('.addressList')[0];
    
    $billingAddressForm.insert({
        'top' : $addressFinderBilling
    });
    
    $billingPostcode.show();
    
    var $shippingAddressForm = $('shipping-new-address-form');
    var $addressFinderShipping = $('addressFinderShipping');
    var $shippingPostcode = $addressFinderShipping.select('.postcode')[0];
    var $shippingAddressList = $addressFinderShipping.select('.addressList')[0];
    
    $shippingAddressForm.insert({
        'top' : $addressFinderShipping
    });
    
    $shippingPostcode.show();
    
    function findAddressFromPostcode(postcode, addressType) {
        new Ajax.Request(
            '<?php echo $this->getUrl('addressfinder/index/findAddressFromPostcode')?>',
            {
                method: 'post',
                parameters: {
                    'postcode'      : postcode,
                    'addressType'   : addressType
                },
                onSuccess: function (transport) {
                    if (addressType === 'shipping') {
                        $shippingAddressList.innerHTML = transport.responseText;
                    }
                    else {
                        $billingAddressList.innerHTML = transport.responseText;
                    }
                },
                onFailure: function() {
                    if (addressType === 'shipping') {
                        $shippingAddressList.innerHTML = '<p>Sorry there has been an error.</p>';
                    }
                    else {
                        $billingAddressList.innerHTML = '<p>Sorry there has been an error.</p>';
                    }
                }
            }
        );
    }

    function populateAddressFields(addressId, addressType) {
        new Ajax.Request(
            '<?php echo $this->getUrl('addressfinder/index/getFullAddress')?>',
            {
                method:'post',
                parameters: {
                    'addressid' : addressId
                },
                onSuccess: function (transport) {
                    var fullAddress = transport.responseText.split('~');
                    if (addressType === 'shipping') {
                        $('shipping:company').value = fullAddress[1];
                        $('shipping:street1').value = fullAddress[2];
                        $('shipping:street2').value = fullAddress[3];
                        $('shipping:region').value = fullAddress[4];
                        $('shipping:city').value = fullAddress[5];
                        $('shipping:postcode').value = fullAddress[6];
                    }
                    else {
                        $('billing:company').value = fullAddress[1];
                        $('billing:street1').value = fullAddress[2];
                        $('billing:street2').value = fullAddress[3];
                        $('billing:region').value = fullAddress[4];
                        $('billing:city').value = fullAddress[5];
                        $('billing:postcode').value = fullAddress[6];
                    }
                },
                onFailure: function() {
                    if (addressType === 'shipping') {
                        $shippingAddressList.innerHTML = '<p>Sorry there has been an error.</p>'
                    }
                    else {
                        $billingAddressList.innerHTML = '<p>Sorry there has been an error.</p>';
                    }
                }
            }
        );
    }
//]]>
</script>